[general]
timezone = "America/New_York"
cache_dir = "data/cache"
results_dir = "data/results"

[filters]
min_hours_ahead = 24
max_hours_ahead = 48
min_edge_pct = 4.0
min_ev = 0.0

[betting]
bankroll = 10000.0
kelly_cap = 0.25
kelly_fraction = 0.5

[leagues]
soccer = ["EPL", "La Liga", "Bundesliga"]
basketball = ["NBA"]
football = ["NFL"]

[providers]
the_odds_api_key = ""
refresh_interval_seconds = 300

[providers.the_odds_api]
enabled = true
base_url = "https://api.the-odds-api.com/v4"

[modeling]
soccer_models = ["poisson", "elo_logistic"]
cv_folds = 5
min_historical_games = 50

[devig]
method = "multiplicative"
